import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get('window'); // Ekran genişliğini alır
const {height} = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#6A0572",
    padding: 20,
  },
  background: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
    backgroundColor: "#6A0572",
  },
  header: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#FFF",
    textAlign: "center",
  },
  title: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#FFD700",
    marginBottom: 20,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  team: {
    paddingTop: 5,
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#FFD700",
  },
  score: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#FFF",
  },
  wordContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  word: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFF",
  },
  bannedTitle: {
    fontSize: 20,
    color: "#FF5733",
    marginTop: 10,
    fontWeight: "bold",
  },
  timer: {
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 10,
    color: "#fff9",
  },
  pass: {
    fontSize: 20,
    marginTop: 5,
    // color: "#D9534F",
    color: "#fff7"
  },
  buttonContainer: {
    flexDirection: "row",
    marginTop: 20,
    justifyContent: "space-between",
    width: "90%",
  },
  input: {
    width: "80%",
    borderBottomWidth: 2,
    borderBottomColor: "#FFF",
    fontSize: 20,
    marginBottom: 15,
    textAlign: "center",
    color: "#FFF",
    padding: 10,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
  },
  winner: {
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#FFD700",
    textAlign: "center",
  },
  historyItem: {
    fontSize: 18,
    marginBottom: 5,
    color: "#EEE",
    textAlign: "center",
  },
  scoreBoard: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    padding: 15,
    backgroundColor: "#ff6f61",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  scoreText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "white",
  },
  roundText: {
    fontSize: 14,
    color: "white",
  },
  card: {
    height: height * 0.45,
    width: width * 0.8,
    padding: 25,
    borderRadius: 20,
    backgroundColor: "#6A0572",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 2,
    borderColor: "#FFD700",
  },
  mainWord: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 15,
  },
  bannedContainer: {
    marginTop: 15,
    alignItems: "center"
  },
  bannedWord: {
    paddingBottom:10,
    fontSize: 24,
    color: "#FFD700",
    fontWeight: "bold",
  },
  button: {
    backgroundColor: "#ff6f61",
    paddingVertical: 15,
    width: "80%",
    borderRadius: 12,
    alignItems: "center",
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FFF",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF",
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    marginBottom: 10,
  },
  inputButton: {
    backgroundColor: "#ff6f61",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    width:30,
  },
  inputButtonText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FFF",
  },
  inputValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    minWidth: 50,
    textAlign: "center",
  },
  startButton: {
    width: 200,
    paddingVertical: 15,
    borderRadius: 30,
    alignItems: 'center',
  },
  startButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  shadow: {
    elevation: 5, // Android gölge efekti
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  logo: {
    width: "60%", // Logonun genişliği
  },
  settingContainer: {
    marginVertical: 20,
    alignItems: "center",
    backgroundColor: "#FFF",
    padding: 15,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width: "90%",
  },
  settingLabel: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
  },
  soundToggleButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  soundOn: {
    backgroundColor: "#28A745",
  },
  soundOff: {
    backgroundColor: "#D9534F",
  },
  soundToggleText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFF",
  },
  
});
